title: Jessica M. Rudd, PhD # your name (or website title) here

logo: "/images/GRAD_011020_JRudd_resize.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
    <p align="center">
    <a href="https://github.com/jrudd1">GitHub</a> |
    <a href="https://www.linkedin.com/in/jmrudd/">LinkedIn</a> |
    <a href="https://twitter.com/funsizeathlete">Twitter</a> 
    <a href="https://medium.com/@funsizeathlete">Medium</a> 
    </p>
    
    <p align="justify">
    Data Science Unicorn | A42 Labs, Inc. | Statistician | Epidemiologist.
    </p>
    <p align="center">   
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
